<a href="https://colab.research.google.com/github/Bhuvi564/covidmlproj/blob/main/COVID(ml).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
data_set = pd.read_csv('Covid_Data_new.csv')
X = data_set.iloc[:, :-1].values
y = data_set.iloc[:, -1].values

In [ ]:
print(X)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' nan]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [nan 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' 'no' 'no' 89.0]
 [35.0 'Modera

In [ ]:
print(y)

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'No' 'Yes' 'Yes' 'Yes']


In [ ]:
from sklearn.impute import SimpleImputer
impute = SimpleImputer(missing_values = np.nan, strategy = 'mean')

impute.fit(X[:, 0:1])
X[:, 0:1] = impute.transform(X[:, 0:1])

impute.fit(X[:, 4:5])
X[:, 4:5] = impute.transform(X[:, 4:5])

In [ ]:
print(X)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' 82.07246376811594]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [45.130434782608695 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' '

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 10.0 97.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 12.0 97.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 15.0 94.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 10.0 97.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 13.0 94.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 12.0 97.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 13.0 93.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 15.0 92.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 18.0 66.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 19.0 92.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 20.0 93.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 17.0 93.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 16.0 92.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 18.0 93.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 20.0 92.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 25.0 93.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 24.0 92.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 26.0 94.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 28.0 99.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 29.0 93.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 30.0 62.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 19.0 89.0]
 [1.0 0.0 

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)


In [ ]:
print(y)

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state = 40)

In [ ]:
print(X_train)

[[1.0 0.0 0.0 1.0 1.0 0.0 0.0 1.0 70.0 88.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 28.0 99.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 18.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 62.0 68.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 74.0 75.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 90.0 67.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 42.0 92.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 94.0 64.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 10.0 97.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.0 1.0 25.0 86.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 1.0 0.0 56.0 76.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 52.0 80.0]
 [0.0 1.0 0.0 0.0 0.0 1.0 1.0 0.0 45.130434782608695 90.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 20.0 92.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 25.0 93.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 35.0 92.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 18.0 66.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 75.0 72.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 1.0 0.0 68.0 67.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 40.0 90.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 19.0 92.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 32.0 84

In [ ]:
print(X_test)

[[1.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 60.0 68.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 10.0 97.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 80.0 92.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 64.0 73.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 35.0 89.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 19.0 89.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 13.0 94.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 28.0 89.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 1.0 0.0 59.0 68.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 81.0 75.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 26.0 94.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 13.0 93.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 58.0 70.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 50.0 77.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 1.0 0.0 36.0 90.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 30.0 62.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 63.0 66.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 56.0 77.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 1.0 0.0 46.0 91.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 32.0 89.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 61.0 76.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 54.0 70.0]
 [1.0 0.0 

In [ ]:
print(y_train)

[0 0 0 1 1 1 0 1 0 0 1 1 0 0 0 0 1 1 1 0 0 0 1 1 0 1 0 0 1 0 1 1 1 1 0]


In [ ]:
print(y_test)

[1 0 0 1 0 0 0 0 1 1 0 0 1 1 0 1 1 1 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 1 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 6:] = sc.fit_transform(X_train[:, 6:])
X_test[:, 6:] = sc.fit_transform(X_test[:, 6:])

In [ ]:
print(X_train)

[[1.0 0.0 0.0 1.0 1.0 0.0 -0.9718253158075504 0.9718253158075504
  0.8834362001297471 0.5504991160885059]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0289915108550531 -1.0289915108550531
  -0.8012213253291784 1.5138725692433903]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0289915108550531 -1.0289915108550531
  -1.202330259962256 0.988396140249817]
 [1.0 0.0 1.0 0.0 0.0 1.0 -0.9718253158075504 0.9718253158075504
  0.5625490524232851 -1.2010889805567384]
 [1.0 0.0 1.0 0.0 0.0 1.0 -0.9718253158075504 0.9718253158075504
  1.0438797739829782 -0.5880331467309029]
 [1.0 0.0 1.0 0.0 0.0 1.0 -0.9718253158075504 0.9718253158075504
  1.6856540693959021 -1.2886683853890006]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0289915108550531 -1.0289915108550531
  -0.23966881684286995 0.9008167354175548]
 [1.0 0.0 1.0 0.0 0.0 1.0 -0.9718253158075504 0.9718253158075504
  1.8460976432491332 -1.5514065998857873]
 [1.0 0.0 0.0 1.0 1.0 0.0 1.0289915108550531 -1.0289915108550531
  -1.523217407668718 1.3387137595788658]
 [1.0 0.0 0.0 1.0 1.0 0.0 -0.97182531580

In [ ]:
print(X_test)

[[1.0 0.0 1.0 0.0 0.0 1.0 -1.3008872711759814 1.3008872711759814
  0.7903766762807177 -1.239957882075372]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.7687061147858072 -0.7687061147858072
  -1.4405252325761466 1.2518771328786795]
 [1.0 0.0 1.0 0.0 1.0 0.0 -1.3008872711759814 1.3008872711759814
  1.6827374398234636 0.8222504061624637]
 [1.0 0.0 1.0 0.0 0.0 1.0 -1.3008872711759814 1.3008872711759814
  0.9688488289892669 -0.8103311553591562]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.7687061147858072 -0.7687061147858072
  -0.3250742781477145 0.5644743701327342]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.7687061147858072 -0.7687061147858072
  -1.0389628889819111 0.5644743701327342]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.7687061147858072 -0.7687061147858072
  -1.3066711180447348 0.99410109684895]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.7687061147858072 -0.7687061147858072
  -0.6374005453876755 0.5644743701327342]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.7687061147858072 -0.7687061147858072
  0.7457586381035805 -1.239957882075372]
 [1.0 0.0 1.0 0.0 0.0 1.0 -1.3008872711759

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


In [ ]:
classifier = LogisticRegression(random_state=42)
classifier.fit(X_train, y_train)


LogisticRegression(random_state=42)

In [ ]:
y_pred = classifier.predict(X_test)


In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100} %")


NameError: name 'accuracy_score' is not defined

In [ ]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   age                           69 non-null     float64
 1   body_temperature              70 non-null     object 
 2   chronic_disease               70 non-null     object 
 3   breathing_issue               70 non-null     object 
 4   Blood O2 Level in Percentage  69 non-null     float64
 5   Needed Hospitalization        70 non-null     object 
dtypes: float64(2), object(4)
memory usage: 3.4+ KB


# New Section