<a href="https://colab.research.google.com/github/Bhuvi564/covidmlproj/blob/main/COVID(ml).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [104]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [105]:
data_set = pd.read_csv('Covid_Data_new.csv')
X = data_set.iloc[:, :-1].values
y = data_set.iloc[:, -1].values

In [106]:
print(X)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' nan]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [nan 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' 'no' 'no' 89.0]
 [35.0 'Modera

In [107]:
print(y)

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'No' 'Yes' 'Yes' 'Yes']


In [108]:
from sklearn.impute import SimpleImputer
impute = SimpleImputer(missing_values = np.nan, strategy = 'mean')

impute.fit(X[:, 0:1])
X[:, 0:1] = impute.transform(X[:, 0:1])

impute.fit(X[:, 4:5])
X[:, 4:5] = impute.transform(X[:, 4:5])

In [109]:
print(X)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' 82.07246376811594]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [45.130434782608695 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' '

In [121]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [122]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [123]:
print(X)

[[1.0 0.0 0.0 1.0 10.0 0 0 97.0]
 [1.0 0.0 0.0 1.0 12.0 0 0 97.0]
 [1.0 0.0 0.0 1.0 15.0 0 0 94.0]
 [1.0 0.0 0.0 1.0 10.0 0 0 97.0]
 [0.0 1.0 0.0 0.0 13.0 0 0 94.0]
 [0.0 1.0 0.0 0.0 12.0 0 0 97.0]
 [0.0 1.0 0.0 0.0 13.0 0 0 93.0]
 [0.0 1.0 0.0 0.0 15.0 0 0 92.0]
 [0.0 1.0 0.0 0.0 18.0 0 0 66.0]
 [1.0 0.0 0.0 1.0 19.0 0 0 92.0]
 [1.0 0.0 0.0 1.0 20.0 0 0 93.0]
 [1.0 0.0 0.0 1.0 17.0 0 0 93.0]
 [1.0 0.0 0.0 1.0 16.0 0 0 92.0]
 [1.0 0.0 0.0 1.0 18.0 0 0 93.0]
 [1.0 0.0 0.0 1.0 20.0 0 0 92.0]
 [0.0 1.0 0.0 0.0 25.0 0 0 93.0]
 [0.0 1.0 0.0 0.0 24.0 0 0 92.0]
 [1.0 0.0 1.0 0.0 26.0 0 0 94.0]
 [1.0 0.0 0.0 1.0 28.0 0 0 99.0]
 [1.0 0.0 0.0 1.0 29.0 0 0 93.0]
 [0.0 1.0 0.0 0.0 30.0 0 0 62.0]
 [1.0 0.0 0.0 1.0 19.0 0 0 89.0]
 [1.0 0.0 0.0 1.0 25.0 0 1 86.0]
 [1.0 0.0 0.0 1.0 26.0 0 0 82.07246376811594]
 [1.0 0.0 0.0 1.0 28.0 0 0 89.0]
 [0.0 1.0 0.0 0.0 30.0 1 0 86.0]
 [0.0 1.0 0.0 0.0 35.0 0 0 89.0]
 [0.0 1.0 0.0 0.0 32.0 0 1 84.0]
 [0.0 1.0 0.0 0.0 45.130434782608695 1 0 90.0]
 [0.0 1.0 0.0 0.

In [124]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)


In [125]:
print(y)

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1]


In [126]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state = 40)

In [127]:
print(X_train)

[[1.0 0.0 0.0 1.0 70.0 0 1 88.0]
 [1.0 0.0 0.0 1.0 28.0 0 0 99.0]
 [1.0 0.0 0.0 1.0 18.0 0 0 93.0]
 [1.0 0.0 1.0 0.0 62.0 1 1 68.0]
 [1.0 0.0 1.0 0.0 74.0 1 1 75.0]
 [1.0 0.0 1.0 0.0 90.0 1 1 67.0]
 [1.0 0.0 1.0 0.0 42.0 0 0 92.0]
 [1.0 0.0 1.0 0.0 94.0 1 1 64.0]
 [1.0 0.0 0.0 1.0 10.0 0 0 97.0]
 [1.0 0.0 0.0 1.0 25.0 0 1 86.0]
 [1.0 0.0 1.0 0.0 56.0 1 0 76.0]
 [1.0 0.0 1.0 0.0 52.0 1 1 80.0]
 [0.0 1.0 0.0 0.0 45.130434782608695 1 0 90.0]
 [1.0 0.0 0.0 1.0 20.0 0 0 92.0]
 [0.0 1.0 0.0 0.0 25.0 0 0 93.0]
 [0.0 1.0 0.0 0.0 35.0 0 1 92.0]
 [0.0 1.0 0.0 0.0 18.0 0 0 66.0]
 [1.0 0.0 1.0 0.0 75.0 0 1 72.0]
 [1.0 0.0 1.0 0.0 68.0 1 0 67.0]
 [0.0 1.0 0.0 0.0 40.0 0 1 90.0]
 [1.0 0.0 0.0 1.0 19.0 0 0 92.0]
 [0.0 1.0 0.0 0.0 32.0 0 1 84.0]
 [1.0 0.0 1.0 0.0 82.0 1 1 73.0]
 [1.0 0.0 1.0 0.0 62.0 1 1 69.0]
 [1.0 0.0 0.0 1.0 20.0 0 0 93.0]
 [1.0 0.0 1.0 0.0 38.0 0 0 75.0]
 [1.0 0.0 0.0 1.0 29.0 0 0 93.0]
 [0.0 1.0 0.0 0.0 61.0 0 1 90.0]
 [1.0 0.0 1.0 0.0 76.0 1 1 80.0]
 [1.0 0.0 0.0 1.0 16.0 0 0 92

In [128]:
print(X_test)

[[1.0 0.0 1.0 0.0 60.0 1 1 68.0]
 [1.0 0.0 0.0 1.0 10.0 0 0 97.0]
 [1.0 0.0 1.0 0.0 80.0 0 1 92.0]
 [1.0 0.0 1.0 0.0 64.0 1 1 73.0]
 [0.0 1.0 0.0 0.0 35.0 0 0 89.0]
 [1.0 0.0 0.0 1.0 19.0 0 0 89.0]
 [0.0 1.0 0.0 0.0 13.0 0 0 94.0]
 [1.0 0.0 0.0 1.0 28.0 0 0 89.0]
 [1.0 0.0 1.0 0.0 59.0 1 0 68.0]
 [1.0 0.0 1.0 0.0 81.0 1 1 75.0]
 [1.0 0.0 1.0 0.0 26.0 0 0 94.0]
 [0.0 1.0 0.0 0.0 13.0 0 0 93.0]
 [1.0 0.0 1.0 0.0 58.0 0 0 70.0]
 [1.0 0.0 1.0 0.0 50.0 1 1 77.0]
 [1.0 0.0 1.0 0.0 36.0 1 0 90.0]
 [0.0 1.0 0.0 0.0 30.0 0 0 62.0]
 [1.0 0.0 1.0 0.0 63.0 1 1 66.0]
 [1.0 0.0 1.0 0.0 56.0 1 1 77.0]
 [1.0 0.0 1.0 0.0 46.0 1 0 91.0]
 [0.0 1.0 0.0 0.0 32.0 0 0 89.0]
 [1.0 0.0 1.0 0.0 61.0 1 1 76.0]
 [1.0 0.0 1.0 0.0 54.0 1 1 70.0]
 [1.0 0.0 0.0 1.0 12.0 0 0 97.0]
 [0.0 1.0 0.0 0.0 24.0 0 0 92.0]
 [0.0 1.0 0.0 0.0 12.0 0 0 97.0]
 [1.0 0.0 1.0 0.0 84.0 1 1 75.0]
 [1.0 0.0 1.0 0.0 40.0 0 0 92.0]
 [1.0 0.0 0.0 1.0 15.0 0 0 94.0]
 [1.0 0.0 1.0 0.0 53.0 1 0 55.0]
 [0.0 1.0 0.0 0.0 48.0 0 1 93.0]
 [1.0 0.0 

In [129]:
print(y_train)

[0 0 0 1 1 1 0 1 0 0 1 1 0 0 0 0 1 1 1 0 0 0 1 1 0 1 0 0 1 0 1 1 1 1 0]


In [130]:
print(y_test)

[1 0 0 1 0 0 0 0 1 1 0 0 1 1 0 1 1 1 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 1 1]


In [131]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 6:] = sc.fit_transform(X_train[:, 6:])
X_test[:, 6:] = sc.fit_transform(X_test[:, 6:])

In [132]:
print(X_train)

[[1.0 0.0 0.0 1.0 70.0 0 0.9718253158075504 0.5504991160885059]
 [1.0 0.0 0.0 1.0 28.0 0 -1.0289915108550531 1.5138725692433903]
 [1.0 0.0 0.0 1.0 18.0 0 -1.0289915108550531 0.988396140249817]
 [1.0 0.0 1.0 0.0 62.0 1 0.9718253158075504 -1.2010889805567384]
 [1.0 0.0 1.0 0.0 74.0 1 0.9718253158075504 -0.5880331467309029]
 [1.0 0.0 1.0 0.0 90.0 1 0.9718253158075504 -1.2886683853890006]
 [1.0 0.0 1.0 0.0 42.0 0 -1.0289915108550531 0.9008167354175548]
 [1.0 0.0 1.0 0.0 94.0 1 0.9718253158075504 -1.5514065998857873]
 [1.0 0.0 0.0 1.0 10.0 0 -1.0289915108550531 1.3387137595788658]
 [1.0 0.0 0.0 1.0 25.0 0 0.9718253158075504 0.3753403064239815]
 [1.0 0.0 1.0 0.0 56.0 1 -1.0289915108550531 -0.5004537418986408]
 [1.0 0.0 1.0 0.0 52.0 1 0.9718253158075504 -0.15013612256959186]
 [0.0 1.0 0.0 0.0 45.130434782608695 1 -1.0289915108550531
  0.7256579257530303]
 [1.0 0.0 0.0 1.0 20.0 0 -1.0289915108550531 0.9008167354175548]
 [0.0 1.0 0.0 0.0 25.0 0 -1.0289915108550531 0.988396140249817]
 [0.0 1.0 0

In [133]:
print(X_test)

[[1.0 0.0 1.0 0.0 60.0 1 1.3008872711759814 -1.239957882075372]
 [1.0 0.0 0.0 1.0 10.0 0 -0.7687061147858072 1.2518771328786795]
 [1.0 0.0 1.0 0.0 80.0 0 1.3008872711759814 0.8222504061624637]
 [1.0 0.0 1.0 0.0 64.0 1 1.3008872711759814 -0.8103311553591562]
 [0.0 1.0 0.0 0.0 35.0 0 -0.7687061147858072 0.5644743701327342]
 [1.0 0.0 0.0 1.0 19.0 0 -0.7687061147858072 0.5644743701327342]
 [0.0 1.0 0.0 0.0 13.0 0 -0.7687061147858072 0.99410109684895]
 [1.0 0.0 0.0 1.0 28.0 0 -0.7687061147858072 0.5644743701327342]
 [1.0 0.0 1.0 0.0 59.0 1 -0.7687061147858072 -1.239957882075372]
 [1.0 0.0 1.0 0.0 81.0 1 1.3008872711759814 -0.63848046467267]
 [1.0 0.0 1.0 0.0 26.0 0 -0.7687061147858072 0.99410109684895]
 [0.0 1.0 0.0 0.0 13.0 0 -0.7687061147858072 0.9081757515057068]
 [1.0 0.0 1.0 0.0 58.0 0 -0.7687061147858072 -1.0681071913888858]
 [1.0 0.0 1.0 0.0 50.0 1 1.3008872711759814 -0.46662977398618366]
 [1.0 0.0 1.0 0.0 36.0 1 -0.7687061147858072 0.6503997154759774]
 [0.0 1.0 0.0 0.0 30.0 0 -0.768

In [134]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


In [135]:
classifier = LogisticRegression(random_state=42)
classifier.fit(X_train, y_train)


LogisticRegression(random_state=42)

In [136]:
y_pred = classifier.predict(X_test)


In [137]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100} %")


Accuracy: 97.14285714285714 %


In [138]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   age                           69 non-null     float64
 1   body_temperature              70 non-null     object 
 2   chronic_disease               70 non-null     object 
 3   breathing_issue               70 non-null     object 
 4   Blood O2 Level in Percentage  69 non-null     float64
 5   Needed Hospitalization        70 non-null     object 
dtypes: float64(2), object(4)
memory usage: 3.4+ KB


# New Section